export const crops = [
  { id:1, name:'Maize (Corn)', category:'Cereals', emoji:'🌽', desc:'Staple food crop grown across East Africa', season:'Mar-May, Sep-Nov', soil:'Well-drained loam', water:'500-800mm/yr', days:'90-120 days', tips:['Plant at start of rains','Space 75cm x 25cm','Apply DAP fertilizer at planting','Top-dress with CAN at knee height'], img:'https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=400&q=80' },
  { id:2, name:'Beans', category:'Legumes', emoji:'🫘', desc:'Rich protein source, grows well with maize', season:'Mar-May, Sep-Nov', soil:'Sandy loam, well-drained', water:'300-400mm/yr', days:'60-90 days', tips:['Intercrop with maize','Inoculate seeds with rhizobium','Avoid waterlogged soils','Harvest when pods dry'], img:'https://images.unsplash.com/photo-1607305387299-a3d9611cd469?w=400&q=80' },
  { id:3, name:'Coffee', category:'Cash Crops', emoji:'☕', desc:'Major export crop, Arabica and Robusta varieties', season:'Year-round', soil:'Deep volcanic loam', water:'1500-2000mm/yr', days:'3-4 years to first harvest', tips:['Shade with banana trees','Prune after harvest','Apply organic mulch','Control CBD with copper spray'], img:'https://images.unsplash.com/photo-1611174743420-3d7df880ce32?w=400&q=80' },
  { id:4, name:'Bananas (Matooke)', category:'Fruits', emoji:'🍌', desc:'Ugandas staple food, cooking and dessert types', season:'Year-round', soil:'Deep rich loam', water:'1200mm/yr', days:'9-12 months', tips:['Plant suckers 3x3m apart','Remove excess suckers','Apply potassium-rich fertilizer','Prop bunches when forming'], img:'https://images.unsplash.com/photo-1543218024-57a70143c369?w=400&q=80' },
  { id:5, name:'Sweet Potatoes', category:'Tubers', emoji:'🍠', desc:'Hardy tuber crop with high nutritional value', season:'Can grow year-round', soil:'Sandy loam', water:'500-750mm/yr', days:'3-5 months', tips:['Plant vines 30cm apart','Ridge the soil','Harvest before heavy rains','Store in cool dry place'], img:'https://images.unsplash.com/photo-1596097635121-14b63b7a0c19?w=400&q=80' },
  { id:6, name:'Tomatoes', category:'Vegetables', emoji:'🍅', desc:'High-value vegetable with strong market demand', season:'Dry season (irrigation)', soil:'Well-drained loam', water:'600mm/yr', days:'60-80 days', tips:['Stake plants early','Remove side shoots','Spray for blight weekly','Harvest when fully ripe'], img:'https://images.unsplash.com/photo-1546470427-e26264be0b0d?w=400&q=80' },
  { id:7, name:'Groundnuts', category:'Legumes', emoji:'🥜', desc:'Nutritious cash and food crop across Uganda', season:'Mar-May, Sep-Nov', soil:'Sandy loam', water:'400-600mm/yr', days:'90-120 days', tips:['Shell carefully before planting','Plant on ridges','Weed early and often','Dry well before storage'], img:'https://images.unsplash.com/photo-1567306226416-28f0efdc88ce?w=400&q=80' },
  { id:8, name:'Rice', category:'Cereals', emoji:'🌾', desc:'Increasingly grown in Ugandas wetlands and uplands', season:'Mar-Jun', soil:'Clay or paddy soil', water:'1200mm+/yr', days:'90-150 days', tips:['Level the field well','Transplant seedlings at 21 days','Flood-irrigate paddy rice','Drain 2 weeks before harvest'], img:'https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=400&q=80' },
];

export const livestock = [
  { id:1, name:'Dairy Cows', category:'Cattle', emoji:'🐄', desc:'Milk production, Friesian and local breeds', breeds:['Friesian','Jersey','Ankole','Crossbreeds'], feeding:'15-20kg dry matter/day', water:'50-100L/day', tips:['Vaccinate against FMD & brucellosis','Deworm every 3 months','Milk twice daily at 12hr intervals','Keep records of milk production'], img:'https://images.unsplash.com/photo-1528127269322-539801943592?w=400&q=80' },
  { id:2, name:'Beef Cattle', category:'Cattle', emoji:'🐂', desc:'Meat production, Ankole and crossbreeds', breeds:['Ankole','Boran','Zebu','Crossbreeds'], feeding:'10-15kg dry matter/day', water:'30-50L/day', tips:['Castrate males early','Brand for identification','Provide mineral licks','Vaccinate against anthrax'], img:'https://images.unsplash.com/photo-1596733430284-f7437764b1a9?w=400&q=80' },
  { id:3, name:'Goats', category:'Goats', emoji:'🐐', desc:'Dairy and meat goats, Boer and local breeds', breeds:['Boer','Kiko','Nubian','Local Mubende'], feeding:'2-3kg dry matter/day', water:'2-4L/day', tips:['Deworm every 6-8 weeks','House off ground to prevent disease','Separate bucks from does','Trim hooves regularly'], img:'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=400&q=80' },
  { id:4, name:'Chickens (Layers)', category:'Poultry', emoji:'🐔', desc:'Egg production, commercial and local breeds', breeds:['Kuroiler','KARI Improved Kienyeji','Rhode Island Red','Leghorn'], feeding:'120g layer mash/day', water:'300-500ml/day', tips:['Provide 16hr light cycle for layers','Vaccinate for Newcastle disease','Collect eggs 3x daily','Cull poor layers'], img:'https://images.unsplash.com/photo-1548550023-2bdb3c5beed7?w=400&q=80' },
  { id:5, name:'Pigs', category:'Pigs', emoji:'🐷', desc:'Fast-growing meat animal with good ROI', breeds:['Large White','Landrace','Duroc','Local'], feeding:'2-3kg feed/day', water:'10-15L/day', tips:['Vaccinate against swine fever','Keep pen clean and dry','Provide wallowing area','Wean piglets at 3-4 weeks'], img:'https://images.unsplash.com/photo-1516467508483-a7212febe31a?w=400&q=80' },
  { id:6, name:'Sheep', category:'Sheep', emoji:'🐑', desc:'Meat and wool production, hardy animals', breeds:['Dorper','Merino','Ugandan Blackhead','Cameroon'], feeding:'2-3kg dry matter/day', water:'2-4L/day', tips:['Shear once or twice a year','Foot-rot prevention critical','Supplement with mineral licks','Rotate pastures regularly'], img:'https://images.unsplash.com/photo-1484557985045-edf25e08da73?w=400&q=80' },
  { id:7, name:'Rabbits', category:'Rabbits', emoji:'🐇', desc:'Fast breeding, ideal for small-scale farmers', breeds:['New Zealand White','California','Chinchilla','Local'], feeding:'100-150g pellets/day', water:'200-500ml/day', tips:['Clean hutch daily','Separate does before kindling','Wean kits at 6-8 weeks','Handle gently to reduce stress'], img:'https://images.unsplash.com/photo-1585110396000-c9ffd4e4b308?w=400&q=80' },
  { id:8, name:'Fish (Tilapia)', category:'Fish', emoji:'🐟', desc:'Aquaculture in ponds, fast growing', breeds:['Nile Tilapia','Catfish','Trout'], feeding:'3% body weight/day', water:'Pond management', tips:['Stock at 3-5 fish/m2','Feed twice daily','Monitor pH and oxygen levels','Harvest at 250-500g'], img:'https://images.unsplash.com/photo-1535591273668-578e31182c4f?w=400&q=80' },
];

export const seasons = [
  { name:'First Rains', months:'March - May', color:'#4a9b6f', bg:'#e8f5ee', icon:'🌧️', desc:'Main planting season. Plant maize, beans, groundnuts, and vegetables. Prepare land in February.', crops:['Maize','Beans','Groundnuts','Tomatoes','Vegetables'] },
  { name:'Dry Season', months:'June - August', color:'#d4860a', bg:'#fef3e2', icon:'☀️', desc:'Harvest season for first rains crops. Good time for land preparation and applying manure.', crops:['Harvest Maize','Harvest Beans','Coffee harvesting','Land preparation'] },
  { name:'Second Rains', months:'September - November', color:'#2d7a8a', bg:'#e0f4f7', icon:'🌦️', desc:'Second planting season. Plant short-season crops and prepare perennials.', crops:['Beans','Vegetables','Sweet Potatoes','Rice'] },
  { name:'Cool Dry Season', months:'December - February', color:'#8b6914', bg:'#fdf6e3', icon:'🌤️', desc:'Mild dry period. Focus on irrigation crops, land clearing, and planning for first rains.', crops:['Irrigated Tomatoes','Onions','Garlic','Land clearing'] },
];

export const chatChannels = ['General','Crops','Livestock','Diseases','Weather','Market'];
